#!/bin/sh

# Set mdev
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s && echo "mdev is ok......"

# create console and null node for nfsroot
#mknod -m 600 /dev/console c 5 1
#mknod -m 666 /dev/null c 1 3

# Set Global Environment
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH=/system/bin:$PATH
export PATH=$PATH:/opt/bin:/opt/sbin
export LD_LIBRARY_PATH=/system/lib
export LD_LIBRARY_PATH=/thirdlib:$LD_LIBRARY_PATH

# networking
ifconfig lo up
#ifconfig eth0 192.168.1.80

# Start telnet daemon
telnetd &

# Set the system time from the hardware clock
#hwclock -s

KERNEL_VERSION=$(uname -r)
insmod /lib/modules/$KERNEL_VERSION/mt7601Usta.ko

wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf -P /var/run/wpa_supplicant.pid
udhcpc -i wlan0 -p /var/run/udhcpc.pid -s /etc/udhcpc.script -b -x hostname:"$(hostname)"

# Start Motor:
insmod /lib/modules/$KERNEL_VERSION/sample_motor.ko

# Determine the image sensor model:
insmod /lib/modules/$KERNEL_VERSION/sinfo.ko
echo 1 >/proc/jz/sinfo/info
#sensor=$(grep -m1 -oE 'jxf[0-9]*$' /proc/jz/sinfo/info)
insmod /lib/modules/$KERNEL_VERSION/tx-isp.ko
insmod /lib/modules/$KERNEL_VERSION/sensor_jxh62.ko


# Start the image sensor:

# Start User Applications:
bftpd -d
dropbearmulti dropbear -R
lighttpd -f /etc/lighttpd.conf

# Disable motion:
setconf -k m -v -1
# Start RTSP-Server without Audio:
#v4l2rtspserver-master -A -W 1280 -H 960 &
