#!/bin/sh
# Motion detection (must be set before the server starting)
# Set the socket option in order to restart easily the server (socket in use)
echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle

if [ ! -f /etc/motion.conf ]; then
  cp /etc/motion.conf.dist /etc/motion.conf
fi

if [ -f /etc/motion.conf ] ; then
    . /etc/motion.conf 2>/dev/null
    setconf -k r -v ${region_of_interest} 2>/dev/null
    setconf -k m -v ${motion_sensitivity} 2>/dev/null
    setconf -k z -v ${motion_indicator_color} 2>/dev/null
    setconf -k t -v ${motion_tracking} 2>/dev/null
fi;
